In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
iris = pd.read_csv("IRIS.csv")

In [4]:
iris.head(100)

sepal_length  sepal_width  petal_length  petal_width          species
0            5.1          3.5           1.4          0.2      Iris-setosa
1            4.9          3.0           1.4          0.2      Iris-setosa
2            4.7          3.2           1.3          0.2      Iris-setosa
3            4.6          3.1           1.5          0.2      Iris-setosa
4            5.0          3.6           1.4          0.2      Iris-setosa
..           ...          ...           ...          ...              ...
95           5.7          3.0           4.2          1.2  Iris-versicolor
96           5.7          2.9           4.2          1.3  Iris-versicolor
97           6.2          2.9           4.3          1.3  Iris-versicolor
98           5.1          2.5           3.0          1.1  Iris-versicolor
99           5.7          2.8           4.1          1.3  Iris-versicolor

[100 rows x 5 columns]

In [5]:
iris.shape

(150, 5)

In [6]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [8]:
#Defining the input feature and target feature
x = iris.drop('species',1)
y = iris['species']

In [9]:
#importing the train_test_split 
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y ,test_size = 0.2, random_state = 50)

# LOGISTIC REGRESSION

In [11]:
#importing LogisticRegression library and fitting the model
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train,y_train)

LogisticRegression()

In [12]:
y_pred = log_reg.predict(x_test)


In [18]:
#accuracy score for Logistic regression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy for Logistic Regression is:",accuracy*100,"%")

Accuracy for Logistic Regression is: 96.66666666666667 %


In [14]:
#confusion matrix for logistic regression
conf_matrix = confusion_matrix(y_test,y_pred) 
print("confusion matrix for Logstic Regression is:\n",conf_matrix)

confusion matrix for Logstic Regression is:
 [[ 9  0  0]
 [ 0 11  1]
 [ 0  0  9]]


In [15]:
#Classification report for Logistic Regression
class_report = classification_report(y_test,y_pred)
print("classification_report for Logistic Regression is:\n",class_report)

classification_report for Logistic Regression is:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      0.92      0.96        12
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



# KNN

In [16]:
#importing KNeighborsClassifier library and fitting the model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [17]:
knn_y_pred = knn.predict(x_test)

In [54]:
#accuracy score for KNN
knn_accuracy = accuracy_score(y_test,knn_y_pred)
print("Accuracy for KNN model is:",knn_accuracy*100,"%")

Accuracy for KNN model is: 90.0 %


In [56]:
#confusion matrix for KNN
knn_conf_matrix = confusion_matrix(y_test,knn_y_pred)
print("Confusion Matrix for KNN model is:\n",knn_conf_matrix)

Confusion Matrix for KNN model is:
 [[9 0 0]
 [0 9 3]
 [0 0 9]]


In [62]:
#Classification report for KNN
knn_class_report = classification_report(y_test,y_pred)
print("Classification report for KNN model is:\n",knn_class_report)

Classification report for KNN model is:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      0.92      0.96        12
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

